package Acme::CPANLists::Import::PerlAdvent::2012_12_21;

# DATE
# VERSION

our @Module_Lists = ({description=>"This list is generated by extracting module names mentioned in [http://perladvent.org/2012/2012-12-21.html] (retrieved on 2016-11-06). Visit the URL for the full contents.",entries=>[{module=>"DBIx::Class"},{module=>"DBIx::Class::Helper::ResultSet::CorrelateRelationship"},{module=>"DBIx::Class::Helper::ResultSet::Me"},{module=>"DBIx::Class::Helper::Row::ProxyResultSetMethod"},{module=>"DBIx::Class::Helpers"},{module=>"DBIx::Class::ResultSet"}],summary=>"Modules mentioned in Perl Advent Calendar 2012 (day 21)"});

1;
# ABSTRACT: Modules mentioned in Perl Advent Calendar 2012 (day 21)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in L<http://perladvent.org/2012/2012-12-21.html> (retrieved on 2016-11-06). Visit the URL for the full contents.

