package Acme::CPANLists::Import::PerlAdvent::2012_12_16;

# DATE
# VERSION

our @Module_Lists = ({description=>"This list is generated by extracting module names mentioned in [http://perladvent.org/2012/2012-12-16.html] (retrieved on 2016-11-06). Visit the URL for the full contents.",entries=>[{module=>"Devel::Declare"},{module=>"Function::Parameters"},{module=>"List::MoreUtils"},{module=>"List::Util"},{module=>"Moose"},{module=>"MooseX::Declare"},{module=>"NEXT"},{module=>"PerlX::Maybe"},{module=>"PerlX::QuoteOperator"},{module=>"Safe::Isa"},{module=>"Syntax::Collector"},{module=>"Syntax::Keyword::Junction"},{module=>"Try::Tiny"},{module=>"TryCatch"},{module=>"Web::Simple"},{module=>"aliased"},{module=>"autovivification"},{module=>"mro"},{module=>"true"}],summary=>"Modules mentioned in Perl Advent Calendar 2012 (day 16)"});

1;
# ABSTRACT: Modules mentioned in Perl Advent Calendar 2012 (day 16)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in L<http://perladvent.org/2012/2012-12-16.html> (retrieved on 2016-11-06). Visit the URL for the full contents.

