package Acme::CPANLists::Import::PerlAdvent::2012_12_19;

# DATE
# VERSION

our @Module_Lists = ({description=>"This list is generated by extracting module names mentioned in [http://perladvent.org/2012/2012-12-19.html] (retrieved on 2016-11-06). Visit the URL for the full contents.",entries=>[{module=>"CHI"},{module=>"CHI::Driver::BerkeleyDB"},{module=>"CHI::Driver::File"},{module=>"CHI::Driver::Memcached"},{module=>"CHI::Driver::Memory"},{module=>"CHI::Driver::Redis"},{module=>"DBI"}],summary=>"Modules mentioned in Perl Advent Calendar 2012 (day 19)"});

1;
# ABSTRACT: Modules mentioned in Perl Advent Calendar 2012 (day 19)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in L<http://perladvent.org/2012/2012-12-19.html> (retrieved on 2016-11-06). Visit the URL for the full contents.

