package Acme::CPANLists::Import::PerlAdvent::2012_12_11;

# DATE
# VERSION

our @Module_Lists = ({description=>"This list is generated by extracting module names mentioned in [http://perladvent.org/2012/2012-12-11.html] (retrieved on 2016-11-06). Visit the URL for the full contents.",entries=>[{module=>"IO::Prompt::Hooked"},{module=>"IO::Prompt::Tiny"},{module=>"IO::Prompter"}],summary=>"Modules mentioned in Perl Advent Calendar 2012 (day 11)"});

1;
# ABSTRACT: Modules mentioned in Perl Advent Calendar 2012 (day 11)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in L<http://perladvent.org/2012/2012-12-11.html> (retrieved on 2016-11-06). Visit the URL for the full contents.

