package Acme::CPANLists::Import::PerlAdvent::2012_12_10;

# DATE
# VERSION

our @Module_Lists = ({description=>"This list is generated by extracting module names mentioned in [http://perladvent.org/2012/2012-12-10.html] (retrieved on 2016-11-06). Visit the URL for the full contents.",entries=>[{module=>"Dist::Zilla"},{module=>"Dist::Zilla::Plugin::ShareDir::Tarball"},{module=>"ExtUtils::MakeMaker"},{module=>"File::ShareDir"},{module=>"File::ShareDir::Tarball"},{module=>"Module::Build"},{module=>"Module::Build::CleanInstall"},{module=>"Module::Build::Cookbook"},{module=>"Module::Pluggable"}],summary=>"Modules mentioned in Perl Advent Calendar 2012 (day 10)"});

1;
# ABSTRACT: Modules mentioned in Perl Advent Calendar 2012 (day 10)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in L<http://perladvent.org/2012/2012-12-10.html> (retrieved on 2016-11-06). Visit the URL for the full contents.

