package Acme::CPANLists::Import::PerlAdvent::2012_12_18;

# DATE
# VERSION

our @Module_Lists = ({description=>"This list is generated by extracting module names mentioned in [http://perladvent.org/2012/2012-12-18.html] (retrieved on 2016-11-06). Visit the URL for the full contents.",entries=>[{module=>"AnyEvent"},{module=>"AnyEvent::HTTP"},{module=>"Coro"},{module=>"File::Basename"},{module=>"IO::Async"},{module=>"IO::Lambda"},{module=>"POE"},{module=>"Reflex"},{module=>"Regexp::Common"}],summary=>"Modules mentioned in Perl Advent Calendar 2012 (day 18)"});

1;
# ABSTRACT: Modules mentioned in Perl Advent Calendar 2012 (day 18)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in L<http://perladvent.org/2012/2012-12-18.html> (retrieved on 2016-11-06). Visit the URL for the full contents.

